import type {
  CardPositionDto,
  HistoryMeetingDto,
  LeagueScoreboardDto,
  MatchupHomeDto,
  SlateGameDto,
  StandingDto,
} from "@/application/queries/league-dtos";

export const simulationLeagueSlug = "west-21st-ledger";

export const matchupHomeFixture: MatchupHomeDto = {
  league: {
    name: "Sample League",
    slug: simulationLeagueSlug,
    seasonLabel: "NFL · 2026",
    mode: "SIMULATION",
    week: 6,
    weekState: "CARDS_OPEN",
    commonLockLabel: "Sunday · 12:55 PM ET",
  },
  self: {
    id: "entry-pfeff",
    displayName: "Pfeff",
    initials: "AP",
    record: "3–2",
    seed: 5,
  },
  opponent: {
    id: "entry-mia",
    displayName: "Mia",
    initials: "MC",
    record: "4–1",
    seed: 2,
  },
  rivalryLabel: "Second meeting · Mia leads series 1–0",
  allocation: {
    allocatedCredits: 650,
    remainingCredits: 350,
    positionCount: 3,
    maximumPositions: 20,
    weeklyAllocationCredits: 1_000,
  },
  consequence: {
    record: "A win moves Pfeff to 4–2 and splits the season series.",
    playoff: "Pfeff is the No. 5 seed, one game above the playoff cutline.",
    context: "Second in Points For · 34–11 all-play · 120.50 PF behind Mia",
  },
  nextKickoff: {
    id: "phi-dal",
    awayTeam: "Philadelphia",
    homeTeam: "Dallas",
    kickoffLabel: "Sunday · 1:00 PM ET",
    updateLabel: "Updated 18 sec ago",
    existingPositionLabel: "Philadelphia −3.5 · 250 credits sealed",
  },
  leagueMatchups: [
    {
      id: "pfeff-mia",
      sideA: "Pfeff",
      sideB: "Mia",
      status: "Cards open",
      isViewerMatchup: true,
    },
    {
      id: "joe-ders",
      sideA: "Joe",
      sideB: "Ders",
      status: "Cards open",
      isViewerMatchup: false,
    },
    {
      id: "lee-drew",
      sideA: "Lee",
      sideB: "Drew",
      status: "Card ready",
      isViewerMatchup: false,
    },
    {
      id: "malcolm-sam",
      sideA: "Malcolm",
      sideB: "Sam",
      status: "Cards open",
      isViewerMatchup: false,
    },
    {
      id: "nina-omar",
      sideA: "Nina",
      sideB: "Omar",
      status: "Cards open",
      isViewerMatchup: false,
    },
  ],
};

export const slateFixture: SlateGameDto[] = [
  {
    id: "phi-dal",
    awayTeam: "Philadelphia",
    homeTeam: "Dallas",
    kickoffWindow: "SUN_EARLY",
    kickoffLabel: "Sunday · 1:00 PM ET",
    updateLabel: "Updated 18 sec ago",
    markets: [
      {
        label: "Winner",
        outcomes: [
          {
            id: "phi-ml",
            proposition: "Philadelphia wins the game",
            displayLine: "Philadelphia",
            americanOdds: -185,
            maximumStakeCredits: 1_000,
          },
          {
            id: "dal-ml",
            proposition: "Dallas wins the game",
            displayLine: "Dallas",
            americanOdds: 160,
            maximumStakeCredits: 1_000,
          },
        ],
      },
      {
        label: "Spread",
        outcomes: [
          {
            id: "phi-spread",
            proposition: "Philadelphia −3.5 must win by 4 or more",
            displayLine: "Philadelphia −3.5",
            americanOdds: -110,
            maximumStakeCredits: 1_000,
          },
          {
            id: "dal-spread",
            proposition: "Dallas +3.5 may win or lose by 3 or fewer",
            displayLine: "Dallas +3.5",
            americanOdds: -110,
            maximumStakeCredits: 1_000,
          },
        ],
      },
      {
        label: "Total",
        outcomes: [
          {
            id: "over-505",
            proposition:
              "Philadelphia and Dallas combine for more than 50.5 points",
            displayLine: "Over 50.5",
            americanOdds: -105,
            maximumStakeCredits: 1_000,
          },
          {
            id: "under-505",
            proposition:
              "Philadelphia and Dallas combine for fewer than 50.5 points",
            displayLine: "Under 50.5",
            americanOdds: -115,
            maximumStakeCredits: 1_000,
          },
        ],
      },
    ],
  },
  {
    id: "buf-kc",
    awayTeam: "Buffalo",
    homeTeam: "Kansas City",
    kickoffWindow: "SUN_LATE",
    kickoffLabel: "Sunday · 4:25 PM ET",
    updateLabel: "Updated 31 sec ago",
    markets: [
      {
        label: "Winner",
        outcomes: [
          {
            id: "buf-ml",
            proposition: "Buffalo wins the game",
            displayLine: "Buffalo",
            americanOdds: 175,
            maximumStakeCredits: 1_000,
          },
          {
            id: "kc-ml",
            proposition: "Kansas City wins the game",
            displayLine: "Kansas City",
            americanOdds: -205,
            maximumStakeCredits: 750,
          },
        ],
      },
      {
        label: "Spread",
        outcomes: [
          {
            id: "buf-spread",
            proposition: "Buffalo +4.5 may win or lose by 4 or fewer",
            displayLine: "Buffalo +4.5",
            americanOdds: -110,
            maximumStakeCredits: 1_000,
          },
          {
            id: "kc-spread",
            proposition: "Kansas City −4.5 must win by 5 or more",
            displayLine: "Kansas City −4.5",
            americanOdds: -110,
            maximumStakeCredits: 1_000,
          },
        ],
      },
      {
        label: "Total",
        outcomes: [
          {
            id: "over-475",
            proposition:
              "Buffalo and Kansas City combine for more than 47.5 points",
            displayLine: "Over 47.5",
            americanOdds: -108,
            maximumStakeCredits: 1_000,
          },
          {
            id: "under-475",
            proposition:
              "Buffalo and Kansas City combine for fewer than 47.5 points",
            displayLine: "Under 47.5",
            americanOdds: -112,
            maximumStakeCredits: 1_000,
          },
        ],
      },
    ],
  },
  {
    id: "nyg-chi",
    awayTeam: "New York",
    homeTeam: "Chicago",
    kickoffWindow: "MON_NIGHT",
    kickoffLabel: "Monday · 8:15 PM ET",
    updateLabel: "Updated 44 sec ago",
    markets: [
      {
        label: "Winner",
        outcomes: [
          {
            id: "nyg-ml",
            proposition: "New York wins the game",
            displayLine: "New York",
            americanOdds: 240,
            maximumStakeCredits: 1_000,
          },
          {
            id: "chi-ml",
            proposition: "Chicago wins the game",
            displayLine: "Chicago",
            americanOdds: -280,
            maximumStakeCredits: 750,
          },
        ],
      },
      {
        label: "Spread",
        outcomes: [
          {
            id: "nyg-spread",
            proposition: "New York +6.5 may win or lose by 6 or fewer",
            displayLine: "New York +6.5",
            americanOdds: -105,
            maximumStakeCredits: 1_000,
          },
          {
            id: "chi-spread",
            proposition: "Chicago −6.5 must win by 7 or more",
            displayLine: "Chicago −6.5",
            americanOdds: -115,
            maximumStakeCredits: 1_000,
          },
        ],
      },
      {
        label: "Total",
        outcomes: [
          {
            id: "over-425",
            proposition:
              "New York and Chicago combine for more than 42.5 points",
            displayLine: "Over 42.5",
            americanOdds: -110,
            maximumStakeCredits: 1_000,
          },
          {
            id: "under-425",
            proposition:
              "New York and Chicago combine for fewer than 42.5 points",
            displayLine: "Under 42.5",
            americanOdds: -110,
            maximumStakeCredits: 1_000,
          },
        ],
      },
    ],
  },
];

export const standingsFixture: StandingDto[] = [
  {
    id: "entry-ders",
    seed: 1,
    memberName: "Ders",
    initials: "DS",
    record: "5–0",
    pointsFor: "6,214.55",
    allPlay: "38–7",
    misses: 0,
    movement: "—",
    state: "No. 1 seed",
    isViewer: false,
  },
  {
    id: "entry-mia",
    seed: 2,
    memberName: "Mia",
    initials: "MC",
    record: "4–1",
    pointsFor: "5,982.10",
    allPlay: "36–9",
    misses: 0,
    movement: "↑ 1",
    state: null,
    isViewer: false,
  },
  {
    id: "entry-joe",
    seed: 3,
    memberName: "Joe",
    initials: "JB",
    record: "4–1",
    pointsFor: "5,610.00",
    allPlay: "29–16",
    misses: 0,
    movement: "↓ 1",
    state: null,
    isViewer: false,
  },
  {
    id: "entry-drew",
    seed: 4,
    memberName: "Drew",
    initials: "DR",
    record: "3–2",
    pointsFor: "5,448.40",
    allPlay: "28–17",
    misses: 0,
    movement: "—",
    state: null,
    isViewer: false,
  },
  {
    id: "entry-pfeff",
    seed: 5,
    memberName: "Pfeff",
    initials: "AP",
    record: "3–2",
    pointsFor: "5,861.60",
    allPlay: "34–11",
    misses: 0,
    movement: "↑ 2",
    state: null,
    isViewer: true,
  },
  {
    id: "entry-lee",
    seed: 6,
    memberName: "Lee",
    initials: "LE",
    record: "2–3",
    pointsFor: "5,202.25",
    allPlay: "21–24",
    misses: 1,
    movement: "—",
    state: "Cutline",
    isViewer: false,
  },
  {
    id: "entry-malcolm",
    seed: 7,
    memberName: "Malcolm",
    initials: "MG",
    record: "2–3",
    pointsFor: "4,918.75",
    allPlay: "18–27",
    misses: 0,
    movement: "↓ 2",
    state: null,
    isViewer: false,
  },
  {
    id: "entry-sam",
    seed: 8,
    memberName: "Sam",
    initials: "SK",
    record: "1–4",
    pointsFor: "4,702.00",
    allPlay: "16–29",
    misses: 1,
    movement: "—",
    state: null,
    isViewer: false,
  },
  {
    id: "entry-nina",
    seed: 9,
    memberName: "Nina",
    initials: "NR",
    record: "1–4",
    pointsFor: "4,201.30",
    allPlay: "11–34",
    misses: 0,
    movement: "—",
    state: null,
    isViewer: false,
  },
  {
    id: "entry-omar",
    seed: 10,
    memberName: "Omar",
    initials: "OA",
    record: "0–5",
    pointsFor: "3,880.00",
    allPlay: "4–41",
    misses: 2,
    movement: "—",
    state: null,
    isViewer: false,
  },
];

export const cardPositionsFixture: CardPositionDto[] = [
  {
    id: "receipt-week6-001",
    eventId: "phi-dal",
    eventLabel: "Philadelphia at Dallas",
    kickoffLabel: "Sunday · 1:00 PM ET",
    marketLabel: "Spread",
    displayLine: "Philadelphia −3.5",
    proposition: "Philadelphia −3.5 must win by 4 or more",
    americanOdds: -110,
    stakeCredits: 250,
    maximumReturnLabel: "477.27",
    acceptedAtLabel: "Friday · 8:14:32 PM ET",
    quoteAtLabel: "Friday · 8:14:18 PM ET",
    status: "SEALED",
    receiptHash: "d35d73ca84e6c52f1f6a125f2da7f161",
  },
  {
    id: "receipt-week6-002",
    eventId: "buf-kc",
    eventLabel: "Buffalo at Kansas City",
    kickoffLabel: "Sunday · 4:25 PM ET",
    marketLabel: "Winner",
    displayLine: "Buffalo",
    proposition: "Buffalo wins the game",
    americanOdds: 175,
    stakeCredits: 200,
    maximumReturnLabel: "550.00",
    acceptedAtLabel: "Saturday · 10:03:11 AM ET",
    quoteAtLabel: "Saturday · 10:02:58 AM ET",
    status: "SEALED",
    receiptHash: "5711e77404d3bb7e71a61068ae3906f4",
  },
  {
    id: "receipt-week6-003",
    eventId: "nyg-chi",
    eventLabel: "New York at Chicago",
    kickoffLabel: "Monday · 8:15 PM ET",
    marketLabel: "Total",
    displayLine: "Under 42.5",
    proposition: "New York and Chicago combine for fewer than 42.5 points",
    americanOdds: -110,
    stakeCredits: 200,
    maximumReturnLabel: "381.82",
    acceptedAtLabel: "Saturday · 4:41:06 PM ET",
    quoteAtLabel: "Saturday · 4:40:51 PM ET",
    status: "SEALED",
    receiptHash: "b5a81f03959378b1ca12ba716e99931d",
  },
];

export const leagueScoreboardFixture: LeagueScoreboardDto[] = [
  {
    id: "pfeff-mia",
    sideA: { name: "Pfeff", record: "3–2", cardState: "650 allocated" },
    sideB: { name: "Mia", record: "4–1", cardState: "Sealed" },
    isViewerMatchup: true,
  },
  {
    id: "joe-ders",
    sideA: { name: "Joe", record: "4–1", cardState: "Cards open" },
    sideB: { name: "Ders", record: "5–0", cardState: "Cards open" },
    isViewerMatchup: false,
  },
  {
    id: "lee-drew",
    sideA: { name: "Lee", record: "2–3", cardState: "Card ready" },
    sideB: { name: "Drew", record: "3–2", cardState: "Cards open" },
    isViewerMatchup: false,
  },
  {
    id: "malcolm-sam",
    sideA: { name: "Malcolm", record: "2–3", cardState: "Cards open" },
    sideB: { name: "Sam", record: "1–4", cardState: "Cards open" },
    isViewerMatchup: false,
  },
  {
    id: "nina-omar",
    sideA: { name: "Nina", record: "1–4", cardState: "Cards open" },
    sideB: { name: "Omar", record: "0–5", cardState: "Cards open" },
    isViewerMatchup: false,
  },
];

export const historyMeetingsFixture: HistoryMeetingDto[] = [
  {
    week: 1,
    scope: "Regular season",
    opponent: "Mia",
    viewerScore: "918.18",
    opponentScore: "1,104.50",
    result: "L",
    note: "Opening-week meeting",
  },
  {
    week: 2,
    scope: "Regular season",
    opponent: "Omar",
    viewerScore: "1,215.00",
    opponentScore: "830.00",
    result: "W",
    note: "First official win",
  },
  {
    week: 3,
    scope: "Regular season",
    opponent: "Drew",
    viewerScore: "1,078.42",
    opponentScore: "1,011.36",
    result: "W",
    note: "Closest win",
  },
  {
    week: 4,
    scope: "Regular season",
    opponent: "Ders",
    viewerScore: "1,366.00",
    opponentScore: "1,512.75",
    result: "L",
    note: "High-scoring loss",
  },
  {
    week: 5,
    scope: "Regular season",
    opponent: "Lee",
    viewerScore: "1,284.00",
    opponentScore: "944.18",
    result: "W",
    note: "Official through Week 5",
  },
];
